# .github/workflows/terraform-frontend-deploy.yml
name: Deploy Streamlit Frontend to Azure with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-frontend:
    name: Terraform Plan & Apply (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra_frontend
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_app_name: ${{ secrets.AZURE_WEBAPP_NAME }}
      TF_VAR_resource_group: rg-tfstate
      TF_VAR_location: EastUS
      TF_VAR_app_service_plan: ${{ secrets.AZURE_WEBAPP_PLAN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          CREDS: ${{ secrets.AZURE_LOGIN_SP_CREDENTIALS }}
          
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false -input=false -var-file="terraform.tfvars"

      - name: Post deployment - Show Web App URL
        run: |
          echo "Deployed to: https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
